### ISSUE TITLE
Loading kinvey with webpack

### ISSUE THREAD

**Issue by se-fDelpech** [Kinvey/angular-sdk#2]
Hi,
I'm currently trying to load Kinvey-angular with Webpack but I'm not able to make it working. 
Regarding to Package.json, `main:` is pointing to a wrong file, it should be `./dist/kinvey.js`. But even after making the change, I'm having some issues.
After trying with others Kinvey lib, the only one I could make working with Webpack was Kinvey-nodejs. But this lib does not have all features related to the client side (offline mode..).
Would that be possible to make your lib compatible with Webpack?
Thanks.

**EDIT:** I just saw that another issue was logged related to webpack ([#1](https://github.com/Kinvey/angular-sdk/issues/1)) but sounds like it's still not completely fixed.

**Comment by ThomasConner** [comment]
What error are using seeing when you try to use the sdk with Webpack?

**Comment by se-fDelpech** [comment]
When linked to `kinvey-angular-sdk/dist/kinvey.js` I have 2 main error:
from Webpack console : 
```
WARNING in ./~/kinvey-angular-sdk/dist/kinvey.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/kinvey-angular-sdk/dist/kinvey.js 1:113-120
```
then from the console log of the browser:
```
Unable to shim indexedDB

angular.js:4495 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.authentication due to:
Error: [$injector:modulerr] Failed to instantiate module kinvey due to:
Error: [$injector:unpr] Unknown provider: $q
...
```

**Comment by ThomasConner** [comment]
We had some issues with out latest beta release of the `Kinvey-Angular-SDK`. We are working on getting a solution out as soon as possible and we will add this to the tickets we would like to resolve for this release. I will respond back in this issue when the new release is available. Thanks for reporting.

**Comment by ThomasConner** [comment]
Are you using bower to install the sdk?

**Comment by se-fDelpech** [comment]
I use npm

**Comment by ThomasConner** [comment]
Please retry using webpack with the latest release (3.0.0-beta.14). I have also updated our [AngularJS Starter App](https://github.com/KinveyApps/AngularJS-Starter) to use webpack.
