### ISSUE TITLE
Unable to open the kid_xyzxyzxzy indexedDB database. undefined."

### ISSUE THREAD

**Issue by lockeyo** [Kinvey/angular-sdk#3]
On iOS / Safari there is an error with indexedDB. Is there a fix for that?

**Comment by lockeyo** [comment]
On the Kinvey Angular SDK with the Version "kinvey-angular-sdk-3.0.0-beta.26.min.js" everything works. Hope I can help you improve your product.

**Comment by ThomasConner** [comment]
@lockeyo Thanks for using the Kinvey Angular SDK. We were not aware of any errors with IndexedDB in iOS / Safari but thank you for finding it. Do you have an error message that might help us know what happened? We certainly would be glad to have help improving the product.

**Comment by lockeyo** [comment]
Here is the error message. ![kinvey-error](https://cloud.githubusercontent.com/assets/5477103/16127459/cd3d2aee-33fc-11e6-82ca-af7762d56192.jpg)

And this is the point where the error is happening.
![code](https://cloud.githubusercontent.com/assets/5477103/16127458/cd099c7e-33fc-11e6-93b7-4285efd3c1eb.jpg)

I'll take a look myself tomorrow and maybe send a Pull request, if I can fix it myself.

**Comment by ThomasConner** [comment]
@lockeyo We recently released [version 3.0.0](http://devcenter.kinvey.com/angular-v3.0/downloads). Was this issue fixed for you?

**Comment by ThomasConner** [comment]
This has been fixed with the release of [version 3.0.0](http://devcenter.kinvey.com/angular-v3.0/downloads).
